### PR TITLE
added project

### PR DESCRIPTION
**Pull request by eleensmathew**
## Added Project

Created page to add project and display them. Modified models and views accordingly.
## Related Issue
I'm currently working on video playing so will like some references on that regard.

Fixes # (https://github.com/ContriHUB/Youdemy/issues/18)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by eleensmathew** [comment]
Fixed the video. All the code works. @kunal2812 Test it out and let me know if you have any comments.

**Review by kunal2812 — CHANGES_REQUESTED** [review]
image

Fix CSS

image

Project Conclusion is asked 2 times (Project should have - Intro, Body, Conclusion)

image

Fix CSS here as well

image

"Blog" in "Projects" page. Center the Project Heading.

I tried adding a Video to Project via both the methods but video is not shown anywhere when I open it.

image

Should have project name there.

**Comment by kunal2812** [comment]
> image
> 
> Fix CSS
> 
> image
> 
> Project Conclusion is asked 2 times (Project should have - Intro, Body, Conclusion)
> 
> image
> 
> Fix CSS here as well
> 
> image
> 
> "Blog" in "Projects" page. Center the Project Heading.
> 
> I tried adding a Video to Project via both the methods but video is not shown anywhere when I open it.
> 
> image
> 
> Should have project name there.

This review was added for changes before your last commit.

**Comment by eleensmathew** [comment]
I fixed the erros check it out and let me know what you think

**Comment by kunal2812** [comment]
What is expected in the Video URL ? I added a youtube video link but getting this
image

**Comment by eleensmathew** [comment]
i figured video url would be in a format that is downloadable. I'll change
the views to accommodate youtube links.

**Comment by kunal2812** [comment]
> i figured video url would be in a format that is downloadable. I'll change the views to accommodate youtube links.

Not needed. I'll try adding a drive video.

**Review by kunal2812 — APPROVED** [review]

**Pull request merged**
