### PR TITLE
designing models for users and completed frontend

### PR DESCRIPTION
**Pull request by eleensmathew**
## Making sign in and sign up functionality

 I have fixed the issue of making the frontend sign in and sign up separate. (I used most of [mangalgithub](https://github.com/mangalgithub) code for the same. If this is plagarism then i will change it). Currently trying to fix the backend.

## Related Issue

Fixes # (https://github.com/ContriHUB/Youdemy/issues/1#issuecomment-1761324404)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by eleensmathew** [comment]
@kunal2812 Its working now. Please check it out.

**Comment by eleensmathew** [comment]
Should I change the home page after the user gets authenticated to not show the sign up and sign in forms?

**Comment by kunal2812** [comment]
Yes

**Comment by eleensmathew** [comment]
Made the necessary changes. Also added the link to profile/ in nav bar. Haven't written profile view  and html page though.

**Comment by kunal2812** [comment]
Can't see any "role" field associated with User model ?

**Comment by eleensmathew** [comment]
fixed it 👍

**Comment by kunal2812** [comment]
LGTM

**Review by kunal2812 — APPROVED** [review]

**Pull request merged**
